defaultBaseImage: registry.access.redhat.com/ubi9/ubi-minimal

baseImageOverrides:
  github.com/shipwright-io/build/cmd/git: saschaschwarze/shipwright-base-git
  github.com/shipwright-io/build/cmd/waiter: ghcr.io/shipwright-io/base-waiter:latest
