---
apiVersion: shipwright.io/v1alpha1
kind: ClusterBuildStrategy
metadata:
  name: buildpacks-v3-heroku
spec:
  buildSteps:
    - name: prepare
      image: heroku/buildpacks:18
      securityContext:
        runAsUser: 0
        capabilities:
          add:
            - CHOWN
      command:
        - chown
      args:
        - -R
        - "1000:1000"
        - /tekton/home
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 65Mi
    - name: build-and-push
      image: heroku/buildpacks:18
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      command:
        - /bin/bash
      args:
        - -c
        - |
          set -euo pipefail

          mkdir /tmp/cache /tmp/layers

          echo "> Processing environment variables..."
          ENV_DIR="/platform/env"

          envs=($(env))

          for env in "${envs[@]}"; do
              IFS='=' read -r key value string <<< "$env"
              if [[ "$key" != "" ]]; then
                  path="${ENV_DIR}/${key}"
                  echo -n "$value" > "$path"
              fi
          done

          /cnb/lifecycle/creator \
            '-app=$(params.shp-source-context)' \
            -cache-dir=/tmp/cache \
            -layers=/tmp/layers \
            -report=/tmp/report.toml \
            '$(params.shp-output-image)'

          # Store the image digest
          grep digest /tmp/report.toml | tr -d ' \"\n' | sed s/digest=// > "$(results.shp-image-digest.path)"
      volumeMounts:
        - mountPath: /platform/env
          name: platform-env
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 65Mi
